name: ML Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision pytest tqdm matplotlib anybadge
        
    - name: Train model
      run: |
        python train.py
        
    - name: Run tests and create badges
      run: |
        python -m pytest test_model.py -v > pytest_output.txt || true
        python create_badge.py
        
    - name: Commit and push badges
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add status-svg/*.svg
        git commit -m "Update status badges" || echo "No changes to commit"
        git push || echo "No changes to push"
      
    - name: Upload badges
      uses: actions/upload-artifact@v4
      with:
        name: badges
        path: 'status-svg/*.svg'
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: model-artifacts
        path: |
          models/
          metrics/
        
    - name: Archive model artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: model_mnist_*.pth