name: ML Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision pytest tqdm matplotlib anybadge
        
    - name: Train model
      run: |
        python train.py
        
    - name: Run tests and create badge
      run: |
        python -m pytest test_model.py -v > pytest_output.txt || true
        python create_badge.py
        
    - name: Upload badges
      uses: actions/upload-artifact@v4
      with:
        name: badges
        path: '*.svg'
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: model-artifacts
        path: |
          models/
          metrics/
        
    - name: Archive model artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: model_mnist_*.pth